# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  core:
    dir: ./core
    taskfile: ./core/Taskfile.yaml

  dashboard:
    dir: ./dashboard
    taskfile: ./dashboard/Taskfile.yaml

  tracker:
    dir: ./tracker
    taskfile: ./tracker/Taskfile.yaml
