// Code generated by ogen, DO NOT EDIT.
package api

type DeleteWebsitesIDRes interface {
	deleteWebsitesIDRes()
}

type GetUsersUserIdRes interface {
	getUsersUserIdRes()
}

type GetWebsitesIDRes interface {
	getWebsitesIDRes()
}

type GetWebsitesRes interface {
	getWebsitesRes()
}

type PatchUsersUserIdRes interface {
	patchUsersUserIdRes()
}

type PatchWebsitesIDRes interface {
	patchWebsitesIDRes()
}

type PostAuthLoginRes interface {
	postAuthLoginRes()
}

type PostAuthRefreshRes interface {
	postAuthRefreshRes()
}

type PostEventHitRes interface {
	postEventHitRes()
}

type PostUserRes interface {
	postUserRes()
}

type PostWebsitesRes interface {
	postWebsitesRes()
}
