root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  args_bin = ["start", "-logger=pretty", "-level=debug", "-corsorigins=http://localhost:8080,http://localhost:5173"]
  bin = "./bin/main"
  cmd = "go build -o ./bin/main ./cmd/"
  delay = 1000
  exclude_dir = ["assets", "bin", "vendor", "testdata", "api", "migrations", "client"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*\\.gen\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml"]
  include_file = []
  kill_delay = "3s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 1000
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true