run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 3m

# This file contains only configs which differ from defaults.
# All possible options can be found here https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
linters-settings:
  exhaustive:
    # Program elements to check for exhaustiveness.
    # Default: [ switch ]
    check:
      - switch
      - map

  govet:
    # Enable all analyzers.
    # Default: false
    enable-all: true
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    # Default: []
    disable:
      - fieldalignment # too strict
      - shadow # too strict

  revive:
    rules:
      - name: unused-parameter
        severity: warning
        arguments:
          - allowRegex: "^_.+$"

linters:
  disable:
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forcetypeassert
    - godox
    - gochecknoglobals
    - interfacebloat
    - ireturn
    - lll
    - nilerr
    - nlreturn
    - paralleltest # TODO: Remove
    - sqlclosecheck # https://github.com/ryanrolds/sqlclosecheck/issues/35
    - tagliatelle
    - varnamelen
    - wsl
    - wrapcheck
  presets:
    - bugs
    - comment
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

issues:
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 20

  exclude-rules:
    - path: "_test\\.go"
      linters:
        - bodyclose
        - goconst
        - gosec
        - noctx

  # Skip auto-generated folders.
  exclude-dirs:
    - api
    - migrations

  exclude-generated: "lax"
