version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
  disable:
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forcetypeassert
    - gochecknoglobals
    - godox
    - interfacebloat
    - ireturn
    - lll
    - nilerr
    - nlreturn
    - paralleltest
    - sqlclosecheck
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    exhaustive:
      check:
        - switch
        - map
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    revive:
      rules:
        - name: unused-parameter
          arguments:
            - allowRegex: ^_.+$
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - goconst
          - gosec
          - noctx
        path: _test\.go
    paths:
      - api
      - migrations
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 20
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  exclusions:
    generated: lax
    paths:
      - api
      - migrations
      - third_party$
      - builtin$
      - examples$
