## Base Go Image
FROM golang:1.21-bullseye AS base
RUN go install github.com/go-task/task/v3/cmd/task@latest

WORKDIR /app
COPY . /app

RUN go mod download
RUN go mod tidy
RUN task build

# Run final binary
CMD ["./bin/main", "start", "-debug"]
