# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  dashboard:
    dir: ../dashboard
    taskfile: ../dashboard/Taskfile.yaml
    internal: true

  tracker:
    dir: ../tracker
    taskfile: ../tracker/Taskfile.yaml
    internal: true

tasks:
  dev:
    # We do not need to embed the dashboard as we run a separate process in development
    # mode.
    deps: [generate:go, tracker:embed]
    cmds:
      - go run -tags "no_duckdb_arrow" ./cmd/ {{.CLI_ARGS}} -logger=pretty -level=debug
    env:
      CGO_ENABLED: "1"

  build:
    deps: [generate]
    cmds:
      - go build -o ./bin/main -tags "no_duckdb_arrow" ./cmd/
    env:
      CGO_ENABLED: "1"

  start:
    deps: [build]
    cmds:
      - ./bin/main {{.CLI_ARGS}}

  release:
    deps: [generate]
    cmds:
      - go build -o ./bin/main -ldflags "-s -w" -trimpath -tags "no_duckdb_arrow" ./cmd/
    env:
      CGO_ENABLED: "1"
      GOEXPERIMENT: "newinliner"

  generate:go:
    cmds:
      - go generate ./...
    sources:
      - ./openapi.yaml
      - ./.ogen.yml
      - ./generate.go
      - ./generate.sh
      - ./go.mod
      - ./go.sum
    generates:
      - ./api/**/*.go

  generate:
    deps: [generate:go, dashboard:embed, tracker:embed]

  update:
    aliases: [upgrade]
    cmds:
      - go get -u ./...
      - go mod tidy

  lint:
    cmds:
      - golangci-lint run ./... --fix

  coverage:
    cmds:
      - go-acc ./... -o coverage.out
      - go tool cover -html=coverage.out

  e2e:
    cmds:
      - docker compose -f compose-test.yaml up --abort-on-container-exit --build

  test:
    deps: [generate]
    cmds:
      - go test -v ./...
    env:
      CGO_ENABLED: "1"
