# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  dashboard:
    dir: ../dashboard
    taskfile: ../dashboard/Taskfile.yaml
    internal: true

  tracker:
    dir: ../tracker
    taskfile: ../tracker/Taskfile.yaml
    internal: true

tasks:
  dev:
    deps: [generate]
    cmds:
      - go run -tags "no_duckdb_arrow" ./cmd/ {{.CLI_ARGS}} -logger=pretty -level=debug -corsorigins=http://localhost:8080,http://localhost:5173
    env:
      CGO_ENABLED: "1"

  build:
    deps: [generate]
    cmds:
      - go build -o ./bin/main -tags "no_duckdb_arrow" ./cmd/
    env:
      CGO_ENABLED: "1"

  start:
    deps: [build]
    cmds:
      - ./bin/main {{.CLI_ARGS}}

  release:
    deps: [generate]
    cmds:
      - go build -o ./bin/main -ldflags "-s -w" -trimpath -tags "no_duckdb_arrow" ./cmd/
    env:
      CGO_ENABLED: "1"
      GOEXPERIMENT: "newinliner"

  generate:go:
    cmds:
      - go generate ./...
    sources:
      - ./openapi.yaml
      - ./.ogen.yml
      - ./generate.go
      - ./generate.sh
      - ./go.mod
      - ./go.sum
    generates:
      - ./api/**/*.go

  generate:
    deps: [generate:go, dashboard:embed, tracker:embed]

  update:
    aliases: [upgrade]
    cmds:
      - go get -u ./...
      - go mod tidy

  fixtures:
    cmds:
      - rm -rf ./db/duckdb/testdata/fixtures/simple.test.db
      - go run ./db/duckdb/testdata

  lint:
    cmds:
      - golangci-lint run ./... --fix

  coverage:
    cmds:
      - go-acc ./... -o coverage.out
      - go tool cover -html=coverage.out

  test:
    deps: [generate:go]
    cmds:
      - go test -v ./...
    env:
      CGO_ENABLED: "1"
