name: Setup Environment
description: Setup the local environment for a Medama workflow

inputs:
  token:
    description: "GitHub token for the repository"
    required: true

runs:
  using: composite
  steps:
    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        repo-token: ${{ inputs.token }}

    - name: Setup Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
      with:
        go-version-file: ./core/go.mod
        cache-dependency-path: ./core/go.sum

    - name: Setup Bun
      uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2
      with:
        bun-version: latest

    - name: Install dashboard dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Generate embeds
      shell: bash
      run: task core:generate
