name: Setup Environment
description: Setup the local environment for a Medama workflow

inputs:
  token:
    description: "GitHub token for the repository"
    required: true

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      with:
        experimental: true
        install: true
        install_args: go bun
        cache: true
        github_token: ${{ inputs.token }}

    - name: Install dashboard dependencies
      shell: bash
      run: bun install --frozen-lockfile

    - name: Generate embeds
      shell: bash
      run: mise run //core:generate
