# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    cmds:
      - task: build:default
      - bun run build:size

  build:default:
    cmds:
      - rm -rf ./dist
      - mkdir -p ./dist
      - bun run build:default
    sources:
      - ./src/*.js
      - ./package.json
      - ./scripts/*.js
    generates:
      - ./dist/*.js

  embed:
    deps: [build:default]
    cmds:
      - mkdir -p ../core/client/scripts
      - |
        for file in ./dist/*.min.js; do
          filename=$(basename "$file")
          cp "$file" "../core/client/scripts/${filename%.min.js}.js"
        done
    sources:
      - ./dist/*.min.js
    generates:
      - ../core/client/scripts/*.js

  test:
    deps: [build:default]
    cmds:
      - bunx playwright test {{.CLI_ARGS}}

  test:ui:
    cmds:
      - bun run e2e:ui

  test:setup:
    cmds:
      - bun playwright install --with-deps chromium firefox webkit chrome msedge

  serve:
    cmds:
      - bun run e2e:serve

  format:
    cmds:
      - bun run format
