# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    cmds:
      - bun run build:default
      - bun run build:size

  build:default:
    cmds:
      - bun run build:default
    sources:
      - ./src/*.js
      - ./package.json
    generates:
      - ./dist/*.js

  embed:
    deps: [build:default]
    cmds:
      - mkdir -p ../core/client
      - cp ./dist/default.min.js ../core/client/script.js
    sources:
      - ./dist/*.min.js
    generates:
      - ../core/client/script.js

  test:
    deps: [build:default]
    cmds:
      - bunx playwright test {{.CLI_ARGS}}

  test:ui:
    cmds:
      - bun run e2e:ui

  serve:
    cmds:
      - bun run e2e:serve
