# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    cmds:
      - npm run build:default
      - bun run build:size

  build:default:
    cmds:
      - npm run build:default
    sources:
      - ./src/default.js
    generates:
      - ./dist/default.js

  embed:
    cmds:
      - mkdir -p ../core/client
      - cp ./dist/default.js ../core/client/script.js
    sources:
      - ./dist/default.js
    generates:
      - ../core/client/script.js

  test:
    cmds:
      - bun run e2e

  test:ui:
    cmds:
      - bun run e2e:ui
