name: Demo Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Docker Edge Publish]
    types: [completed]
    branches: [main]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    # Run only if Docker publish was successful or it is a manual workflow deployment.
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Wait for Docker Edge image to be updated in registry
        run: sleep 45s
        shell: bash

      - uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4
        with:
          experimental: true
          install: true
          install_args: flyctl
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: mise run //:deploy:demo
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
