name: Setup Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      checkout-path: ${{ steps.checkout.outputs.path }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ steps.checkout.outputs.path }}/core/go.mod
          cache-dependency-path: ${{ steps.checkout.outputs.path }}/core/go.sum

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dashboard dependencies
        run: bun install --frozen-lockfile

      - name: Generate embeds
        run: task core:generate
